services:
  laravel:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    container_name: morent-admin-console_laravel
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - mysql
      - minio

  nginx:
    image: nginx:stable-alpine
    container_name: morent-admin-console_nginx
    ports:
      - "7000:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: morent-admin-console_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: morent-admin-console_minio
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  minio-data: