services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_morent_laravel
    ports:
      - "7000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    env_file:
      - .env

volumes:
  mysql-data:
