FROM php:8.2

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    openssh-client \
    && docker-php-ext-install \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    zip \
    opcache

# Install cloudflared
RUN curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared && \
    chmod +x /usr/local/bin/cloudflared

# Configure SSH
RUN mkdir -p /root/.ssh && \
    ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N "" && \
    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts && \
    echo "Host github.com" > /root/.ssh/config && \
    echo "    IdentityFile /root/.ssh/id_rsa" >> /root/.ssh/config && \
    echo "    StrictHostKeyChecking no" >> /root/.ssh/config

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g yarn

# Set the working directory
COPY . /var/www/html
WORKDIR /var/www/html

# Copy entrypoint script
COPY entrypoint.dev.sh /usr/local/bin/

# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/entrypoint.dev.sh

# Use the entrypoint script
ENTRYPOINT ["entrypoint.dev.sh"]